apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LAhcKKKN8d45KM2KSPqEkvpUyRX91rZ3mLY6pfW6m2rpC4Zzk8S2jelu59/Ud12/hoHNV2cKk1LuG1jiBygJ3W9iodT4apQhPw9jmn69cf97k2hQBaoXahZkr5yDYeBzEUNIEteVGgO1/6uH5cx7ARlu1Pel6yMfOsBSpxOoFc4CMvQwYW7y7VB4Jcnj6q2HiAUM9OdEED7miruW5c/8dfIi5Pf5ZD+RyOoShJG0ktjhTbtRncj1vDeP0DL/f45iFnBFZdeaqA8NIxHxaejPx1rp1Plmp756Dmz7sD9dIZ91PUzqWc2QuwtsNmE=,iv:hFeHPPy6TqmIP4D//OaenTqEq6D0N+scRGFl6t1OFJ8=,tag:b27pYg+Wi2KGT9mbg69YPg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1rvdapqhwzmcfnm4nmpqjqpu3ed23nzwumjtyazsglv5ljdpc8a4q39lem8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN3hJQmRZSW9KdEhtM3FG
            Q2JzUzdkbWRGdTlMYUpIdlo4dkdhUTdxYkRnCmg4bFZuM1VxVFM2UGxBbVVocmNq
            NkNMc3d5L2MrTDVTa1M2VjFWUURMdWcKLS0tIE1OUHlTQVE3cDNCSmJUL2JmUXd5
            M2FFcXBQN3RUbDNzOGlReTZJL2pEYncKRgORa3eghFjZwmkZZvi+kZLEb2H8aJDB
            wHvyItrqe5fPoVOU9XqOq2g0Ws1nGmAG92bk5K9yMfvohD/A2oSsDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T17:25:43Z"
    mac: ENC[AES256_GCM,data:hkDrle5nfL3L2DVWjmg7tb4HxWPYTfcgNc0/zm0wiZwFI7zk0JIKJe8HawkslrGWsmQKRFEmQrlwrIqDQ08HV7nP29UVEIyIDAkUuuDWJUUu8PD3/B7pAoiZWuL7cr9WuGmnKPexYqRdDtr5bK3uWbucWeMhU3WV5+Hyk8Mq7zo=,iv:fukfDUDYmzbWDMzkg9gb35vxRNAcgXj/G9hFzIf6ZdE=,tag:S7opi65qoMsft3T22b/sMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
