apiVersion: v1
data:
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:ZZpnApaBdUJqzCPnrMpZF/1poso7r+Hp5FCuos0NJjifkiZo4bmk8qFtf4g=,iv:ffV5r2++7xDld0J0BZgTJ/KIZ+JD/5O80lEPCbg5MqA=,tag:QGr7dCj2VfLxcO/2f2yesQ==,type:str]
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:7KRenVEJI04=,iv:pzBzcGolXpWGEsAZtuu1N7/vUtqHm+Qam+ro1wxVeo0=,tag:tXFzRx3ETbvZHk5/JW0XEw==,type:str]
kind: Secret
metadata:
    name: handlesregister-db-credentials
    namespace: handlesregister-db
sops:
    age:
        - recipient: age1rvdapqhwzmcfnm4nmpqjqpu3ed23nzwumjtyazsglv5ljdpc8a4q39lem8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcXZRSTBESnZwOHcrUkVJ
            dFdwbUlnQnI4Z2NWM0d0NGZCL3hQUkhSTHhBCmZVMVM4d3owR1M4VEd2MGZ3UEJx
            cXdmVmYvVWQ3TWUrZVg1TUV4WVlBQzQKLS0tIHd3YzB5M2VPMElmcVBBQm5XMFVV
            b0p3bk9DdjlvbFo3TDYvMUZuL2NRV2cK67xWqSN43h1f/cr3tYnIhelLSJgMJfgu
            devhfW/5+VHZD5+ou65Yf8mQkPDjw9/PGKPCBnNy92FXWZ3IDx6ekg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T13:35:30Z"
    mac: ENC[AES256_GCM,data:5Nti5PJUMmssRx1u3Hr6vZXS4U+aCzbngeBQC+f/LCVvzBMzsNTSEms8xGBacPuWQwsEmoeFHU8pFX3tcCufSdRgY5BEgNT0gZcq5s4HHJQuKHVstT2fTXrLzPt94m0oo9GUSdLCvbtK5wH5DYDndncvMLYkXYWhVVyG85UKJqY=,iv:8RYHPq+DiIV30QR+e0B3n/Nh4UOXynuY5+UQI+NDUWU=,tag:7+4qIYWnWztUg+PoRkYkJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
