apiVersion: v1
data:
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:3BYPrGDJiaYkrsMa1thjEB6PrAK1fOJbQLRsVlnnvFiyB4Q/67tORYSFiZA=,iv:oNSQqfihGDGZPv3EvK5I1LRo2Bii51Gbwg+IxMsBoL4=,tag:6PZ5IIvXGnLieuVuXtK7Wg==,type:str]
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:ikyx+m5HD04=,iv:MnRuJUTrLdyWhChUiDQVdY/4g9w7dG0L713IK0HyHvw=,tag:CP5mIdw8YkrVIUrikblaeg==,type:str]
kind: Secret
metadata:
    name: handlesregister-db-credentials
    namespace: handlesregister-db
sops:
    age:
        - recipient: age1rvdapqhwzmcfnm4nmpqjqpu3ed23nzwumjtyazsglv5ljdpc8a4q39lem8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZDY3OUErQytTbGt3TUlE
            ZmhwY2xScHdvR0xFTDY0M29lT2x6YnUvckEwCnEyTHN2Q0hxRjNTeFBSd3F5VjZp
            TE1RTHpXblhnS3M0OXVMZ0FwZzVIQmMKLS0tIERTNTNYaUdoVUs5aEoyNStnY2Uz
            MTluM2RBNUFJcjRSUmFPbGVKdFQzRncK6OkgZ2VQHvQKwHE+j9GhYvkRd8PjvblH
            lfaaX/C1Q6Cq5jln+vCqf69F5CYjZ9KIQRu8Jmpr5EdxiAUGn2ygWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T14:11:32Z"
    mac: ENC[AES256_GCM,data:tgbXbqzjxm3c5cNplvibrQLnRdHI5meBLUOSWhHJPWhlX8O5LfLlLPq2HExX1C7NLtzroxiaRJPAWm68dANCuiGnJhv4bVohFmBapqUDdFNRY9mw0TpK5josfAGn4u89YCrFfDBEKx6R8jQBei5mxbDmMpJnxiy36yETTq9M+LY=,iv:YTnghTWlVf+Es+AoOBZTx6Myzt7DAbKVWEpRel03oaI=,tag:z/0tKm6p+7EGdRS3c8YHwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
